#** default.yml **#
#=================================
# Author: newini
# Date: April 2020
# Project: GPS server
# Description: API configure
#=================================


# Token
GPS_SERVER_API_TOKEN: abcd1234


# MongoDB
MONGO_URI: mongodb://127.0.0.1:27017/gps


# Log
logfile_dir_path: /tmp


# for development
host: 0.0.0.0
port: 5001
debug: true
